// src/app/verify/tos/page.tsx
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { CheckCircle, XCircle, Bot } from 'lucide-react';
import Link from 'next/link';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export default async function TosVerificationPage({ searchParams }: { searchParams: { id: string } }) {
    const supabase = createServerComponentClient({ cookies });
    const tosId = searchParams.id;
    let tos: any = null;
    let errorMessage: string | null = null;

    if (tosId) {
        const { data, error } = await supabase.from('tables_of_specification').select('*').eq('id', tosId).single();
        if (error || !data) { errorMessage = "No Table of Specification found for this ID."; } else { tos = data; }
    } else { errorMessage = "No ID provided."; }

    return (
        <div className="min-h-screen bg-gray-50 flex flex-col items-center p-8">
            <main className="w-full max-w-5xl bg-white p-10 rounded-xl shadow-md border">
                <div className="flex justify-between items-center pb-4 border-b">
                    <div><h1 className="text-3xl font-bold">ToS Verification</h1><p className="text-gray-500">Authenticity report from LearnBridgeEdu.</p></div>
                    <Link href="/" className="flex items-center gap-2 font-semibold"><Bot /><span>LearnBridgeEdu</span></Link>
                </div>
                {tos ? (
                    <>
                        <div className="mt-6 flex items-center gap-3 p-4 bg-green-50 text-green-800 rounded-lg"><CheckCircle/><div><h2 className="font-semibold">Document Verified</h2><p className="text-sm">This is an authentic ToS generated by our platform.</p></div></div>
                        <div className="mt-6 space-y-4">
                            <div className="text-center mb-4"><h2 className="text-xl font-bold uppercase">{tos.subject}</h2><p>End of term exams</p></div>
                            <Table className="border">
                                <TableHeader><TableRow><TableHead>Week</TableHead><TableHead>Focal Area(s)</TableHead><TableHead>Type</TableHead><TableHead>DoK 1-4</TableHead><TableHead>Total</TableHead></TableRow></TableHeader>
                                <TableBody>
                                    {tos.tos_data.tosData.map((weekData: any, index: number) => (
                                        <TableRow key={index}><TableCell className="font-semibold">{weekData.weekRange}</TableCell><TableCell className="whitespace-pre-line">{weekData.focalAreas}</TableCell>{/* ... Simplified render for verification ... */}</TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                        </div>
                    </>
                ) : (
                    <div className="mt-6 flex items-center gap-3 p-4 bg-red-50 text-red-800 rounded-lg"><XCircle/><div><h2 className="font-semibold">Verification Failed</h2><p className="text-sm">{errorMessage}</p></div></div>
                )}
            </main>
        </div>
    );
}