// src/app/verify/lesson/page.tsx
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { CheckCircle, XCircle, Bot } from 'lucide-react';
import Link from 'next/link';

interface PlanData {
    activities: { phase: string; teacherActivity: string; learnerActivity: string }[];
    subject: string;
    strand: string;
    subStrand: string;
    contentStandard: string;
    // ... add all other fields from the planData object
}

interface PlanRecord {
  id: string;
  created_at: string;
  plan_data: PlanData;
  subject: string;
  grade: string;
  week: number;
}

export default async function LessonVerificationPage({
  searchParams,
}: {
  searchParams: { id: string };
}) {
    const cookieStore = await cookies();
    const supabase = createServerComponentClient({ cookies: () => cookieStore });
    const planId = searchParams.id;
    let lessonPlan: PlanRecord | null = null;
    let errorMessage: string | null = null;

    if (planId) {
        const { data, error } = await supabase
            .from('lesson_plans')
            .select('*')
            .eq('id', planId)
            .single();

        if (error || !data) {
            errorMessage = "No lesson plan record found for the provided ID.";
        } else {
            lessonPlan = data as PlanRecord;
        }
    } else {
        errorMessage = "No lesson plan ID was provided.";
    }

    return (
        <div className="min-h-screen bg-gray-50 flex flex-col items-center p-4 sm:p-8">
            <main className="w-full max-w-4xl bg-white p-6 sm:p-10 rounded-xl shadow-md border">
                <div className="flex justify-between items-center pb-4 border-b">
                    <div>
                        <h1 className="text-3xl font-bold">Lesson Plan Verification</h1>
                        <p className="text-gray-500">Authenticity report from LearnBridgeEdu.</p>
                    </div>
                    <Link href="/" className="flex items-center gap-2 font-semibold"><Bot className="h-6 w-6 text-brand-primary" /><span>LearnBridgeEdu</span></Link>
                </div>
                
                {lessonPlan ? (
                    <>
                        <div className="mt-6 flex items-center gap-3 p-4 bg-green-50 text-green-800 rounded-lg">
                            <CheckCircle className="h-8 w-8" />
                            <div><h2 className="font-semibold">Document Verified</h2><p className="text-sm">This is an authentic lesson plan generated by our AI platform.</p></div>
                        </div>
                        <div className="mt-6 space-y-4">
                            <h3 className="text-xl font-semibold border-b pb-2">Plan Details</h3>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                                <div><strong>Subject:</strong> {lessonPlan.subject}</div>
                                <div><strong>Class:</strong> {lessonPlan.grade}</div>
                                <div><strong>Week:</strong> {lessonPlan.week}</div>
                                <div><strong>Generated On:</strong> {new Date(lessonPlan.created_at).toLocaleString()}</div>
                            </div>
                            <div className="pt-4">
                                <h4 className="font-semibold mb-2">Content Standard:</h4>
                                <p className="text-sm p-3 bg-gray-50 rounded-md border">{lessonPlan.plan_data.contentStandard}</p>
                            </div>
                            <div className="pt-4">
                                 <h4 className="font-semibold mb-2">Learning Activities:</h4>
                                 <div className="text-sm border rounded-md">
                                    {lessonPlan.plan_data.activities.map((act, index) => (
                                        <div key={index} className="grid grid-cols-3 p-3 border-b last:border-0">
                                            <div className="font-semibold text-orange-700">{act.phase}</div>
                                            <div className="col-span-2">{act.teacherActivity}</div>
                                        </div>
                                    ))}
                                 </div>
                            </div>
                        </div>
                    </>
                ) : (
                     <div className="mt-6 flex items-center gap-3 p-4 bg-red-50 text-red-800 rounded-lg">
                        <XCircle className="h-8 w-8" />
                        <div><h2 className="font-semibold">Verification Failed</h2><p className="text-sm">{errorMessage}</p></div>
                    </div>
                )}
            </main>
        </div>
    );
}

